[package]
name = "variables"
version = "2.3.4"
edition = "2021"
author = ["David Carrington <dmcarrington@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
